### PR TITLE
added unit tests

### PR DESCRIPTION
**Pull request by kamuffe**
Hi @stefanuebe 

I created a first unittest. Is this direction something I can go? Or do you want me to make it another way?

Best,
Kamuffe

### CODE REVIEW

**Comment by stefanuebe** [comment]
Hi Kamuffe, thanks for the work, looks good so far. I would even say you can do it a step simpler and group the multiple tests into one method, e.g. "test_correctDateTimeGetter" or something like that, if you want, too. Spares you some of the writing overhead :)

**Comment by stefanuebe** [comment]
Ah, one thing: the Berlin offset reference day has a fixed +1 offset. That test will most likely fail during summertime, when the offset is +2. Might be better to use the zone rules offset and daylight saving time (or you use the timezone apply offset method, e.g. `berlinTimezone.applyOffset(referenceDate)`. This method's correctness is already tested in another test - theoretically :D)

**Comment by kamuffe** [comment]
> Hi Kamuffe, thanks for the work, looks good so far. I would even say you can do it a step simpler and group the multiple tests into one method, e.g. "test_correctDateTimeGetter" or something like that, if you want, too. Spares you some of the writing overhead :)

This was my first try. You are right. 
But in my experience it's better to have one test method testing just one thing. When something fails you see at the first look whats going wrong. 

If you insist on consolidating these methods, I will do so ;)

**Comment by stefanuebe** [comment]
> I have one question:
> What do you think about moving these events (TimeslotsSelectedEvent, TimeslotsSelectedEvent, ...) into a sub-package "event". To cleanup the code base a little bit?

Jep, good idea, but something to consider for 4.2 or even 5.0, since it will be a breaking change. :)

**Pull request merged**
