### PR TITLE
Fix drop event

### PR DESCRIPTION
**Pull request by aetasoul**
Temporary fix for the drop event.
Enabled drop on same line and between differente resources

### CODE REVIEW

**Comment by stefanuebe** [comment]
Can you please explain the issue in detail? I can dnd calendar entries between resources on the same day without an exception.

**Comment by aetasoul** [comment]
I have one popup that open when:

- dnd an event from "resource 1" to "resource 2"
- dnd an event from "resource 1" to "resource 1"

The popup ask for "Copy" "Move" or "Abort".

When I dnd the event on the same resource but between different days the popup don't appear.
Debugging the code the result is as follow:

```
public EntryDroppedSchedulerEvent(FullCalendarScheduler source, boolean fromClient,
                                      @EventData("event.detail.data") JsonObject jsonEntry,
                                      @EventData("event.detail.delta") JsonObject jsonDelta) {
        super(source, fromClient, jsonEntry, jsonDelta);

        String oldResourceId = jsonEntry.getString("oldResource"); //Exception on this line with the method getString
        if (oldResourceId != null && oldResourceId.length() > 0) {
            this.oldResource = source.getResourceById(oldResourceId).orElseThrow(IllegalArgumentException::new);
        }

        String newResourceId = jsonEntry.getString("newResource");
        if (newResourceId != null && newResourceId.length() > 0) {
            this.newResource = source.getResourceById(newResourceId).orElseThrow(IllegalArgumentException::new);
        }
    }
```

The first case (from "resource 1" to "resource 2") produce the jsonEntry with 6 element inside:

1. id
2. start
3. end
4. allDay
5. oldResource
6. newResource

so when I press copy or move the event contain the correct new resource and I can copy/move between resource.

The second case (from "resource 1" to "resource 1") produce the jsonEntry with 4 elements:

1. id
2. start
3. end
4. allDay

so the `jsonEntry.getString("oldResource");` produce an exception, the event don't execute and the popup don't appear, the event just move into the new date and when I refresh the page it return back to the original position.

```
eventDrop: (eventInfo) => {
                return {
                    //eventInfo.oldResource, eventInfo.newResource
                    data: this._toEventData(eventInfo.event, eventInfo.oldResource, eventInfo.newResource),
                    // data: this._toEventData(eventInfo.event),
                    delta: eventInfo.delta,
                    // oldResource: eventInfo.oldResource ? eventInfo.oldResource.id : null,
                    // newResource: eventInfo.newResource ? eventInfo.newResource.id : null
                }
            },
```

dnd between resources produce the eventInfo.oldResource, eventInfo.newResource as non null value so the _toEventData produce the correct jsonEntry with 6 entry.
The dnd on the same resource produce eventInfo.oldResource, eventInfo.newResource as NULL value, so the _toEventData return the jsonEntry without the oldResource and newResource, and the getString can't find it when called, so create an exception.

**Comment by stefanuebe** [comment]
Ok, got that error, too. I would prefer a solution on the server side to spare unneeded details sent to the server (no need for empty old/newResource property).

I will provide a Java side solution. Thanks for the issue and the PR :)

**Comment by stefanuebe** [comment]
Version 2.2.2 is up, should fix the issue (see EntryDroppedSchedulerEvent)

**Comment by aetasoul** [comment]
Thank you! Now it is working correctly :) 
Sorry for my english during the explaination, but is hard to explain something that you don't know

**Pull request closed without merging**
