### PR TITLE
Upgrade to V5

### PR DESCRIPTION
**Pull request by aetasoul**
According to the [upgrade guide ](https://fullcalendar.io/docs/upgrading-from-v4) I made some changes to:

*  Renamed all the options that has changed the name
*  Changed the `eventRender` with the new event render hooks.
*  Removed the ViewPort

Actually I'm stuck on the CSS conversion. Reading the guide chapter **CSS and DOM Structure** it talk about a *className-upgrade document* that I can't find anywhere.

### CODE REVIEW

**Comment by kamuffe** [comment]
@aetasoul I tried the same locally and stuck at exactly the same stage. I was not able to get the css files in via webpack. And therefore the UI was broken.
@stefanuebe can you somehow assist?
Best,
Kamuffe

**Comment by stefanuebe** [comment]
Hey guys, sorry, totally missed that one. First of all thanks for the support, I'm simply overwhelmed in my current project, that's the reason why I simply have no time to take care about this one. I try to find some time these days to check the CSS thing.

**Comment by stefanuebe** [comment]
I tried this weekend too, to get it running, but wasn't able to get it running, too - but also just had an hour of time to spend, so at the end it might take just some additional time. Sorry to let you guys hanging around with that for so long, time and energy is currently a bit low on my side. I'll try to catch up with it.

**Comment by aetasoul** [comment]
I have found in an [old article](https://fullcalendar.io/blog/2020/02/changes-in-the-upcoming-v5#css-refactor) some reference to make the conversion of the CSS working. 

> FullCalendar’s CSS is being rewritten and DOM structure reduced and simplified, allowing for easier restyling. This is thanks to CSS3 advancements like [flexbox](https://css-tricks.com/snippets/css/a-guide-to-flexbox/). Also, we’re employing a flatter [BEM](https://css-tricks.com/bem-101/)-like classname pattern.

**Comment by aetasoul** [comment]
The new updated version is in merge request #73

**Pull request merged**
