### PR TITLE
Added some features (addChildren to resource and removeAllResource)

### PR DESCRIPTION
**Pull request by aetasoul**
I have added the command removeAllResources to clear all the resources from the scheduler. I have also added the children structure to the Resource class to able the client can collect/store many things in the same place and nest the resources.

### CODE REVIEW

**Comment by stefanuebe** [comment]
Thanks for your contribution :)

**Comment by stefanuebe** [comment]
Attention: I will change some logic behind the resource children to match with the behavior of other containers (e.g. resource entry). This means, that getChildren will return 1) a set and 2) this set will be a unmodifiable copy. The API of the resource will be extended to modify those instances.

**Comment by stefanuebe** [comment]
New version 2.2.0 is uploaded now, please have a look on the changes.

**Comment by aetasoul** [comment]
Thank you stefan, I'm continuously checking your updates!
Is possible to implement the tooltip like [here](https://fullcalendar.io/docs/event-tooltip-demo)

I can't figure out how to add this to the Resource and the resource event...

**Pull request merged**
