### PR TITLE
#110 server timezone

### PR DESCRIPTION
**Pull request by kamuffe**

### CODE REVIEW

**Comment by christophkarmowski** [comment]
What is still needed to complete this PR?

Best,
Kamuffe

**Comment by stefanuebe** [comment]
Sorry, simply oversaw the updated version. Going to review it nearby

**Comment by stefanuebe** [comment]
Short question: have the JUnit tests ran through on your machine?

**Comment by kamuffe** [comment]
I run the EntryTest.
But now I see there are still failing tests. Sorry about that. 

I'll fix them.

**Comment by stefanuebe** [comment]
No need to, I am already on that. There are additional things, that need to be fixed / changed.

**Pull request merged**
